name: Build and Push Docker image

on:
  push:
    branches:
      - main  # jalankan saat push ke branch main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Login ke DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t willdan1453/compiler-judge0-inacomp:latest .

    - name: Push Docker image ke DockerHub
      run: docker push willdan1453/compiler-judge0-inacomp:latest
